# Generated by Django 4.1 on 2023-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_title',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_private',
            field=models.BooleanField(default=False, verbose_name='Приватная'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
