# Generated by Django 4.1 on 2023-01-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articles_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categories',
        ),
    ]
